### ISSUE TITLE
The doc parser doesn't escape HTML tags in procedure arguments

### ISSUE THREAD

**Issue by akmubi** [odin-lang/pkg.odin-lang.org#13]
Looks like the parser doesn't escape HTML tags or something. So [this](https://github.com/odin-lang/Odin/blob/master/core/encoding/hxa/read.odin#L31):
```odin
read :: proc(data: []byte, filename := "<input>", print_error := false, allocator := context.allocator) -> (file: File, err: Read_Error) {}
```

becomes [this](https://pkg.odin-lang.org/core/encoding/hxa/#read):
![bug](https://github.com/odin-lang/Odin/assets/53152392/77111e8d-5f78-459a-9a91-fcdb29771360)

**Comment by Kelimion** [comment]
And now it's on the correct one.
