### ISSUE TITLE
Documentation for darwin packages is not generated

### ISSUE THREAD

**Issue by barnamumtyan** [odin-lang/pkg.odin-lang.org#24]
Documentation for darwin packages, for example Metal are not generated.
https://pkg.odin-lang.org/vendor/darwin/Metal/
I tried generating the documentation on MacOS

it seems that
`odin doc examples/all -all-packages -doc-format -show-debug-messages`
generates the packages
```
[DEBUG] odin_doc_add_pkg_entries writing -> package darwin
...
[DEBUG] odin_doc_add_pkg_entries writing -> package objc_Foundation
[DEBUG] odin_doc_add_pkg_entries writing -> package objc_Metal
[DEBUG] odin_doc_add_pkg_entries writing -> package objc_MetalKit
[DEBUG] odin_doc_add_pkg_entries writing -> package objc_QuartzCore
```
However directx packages are not generated, neither x11 package
Considering that the github actions are run on windows, and directX packages are on the documentation page
odin doc only generates the packages for the host OS

**Comment by gingerBill** [comment]
This is not a bug, and just how the _compiler_ itself works. It cannot type check things it cannot see because of the target platform.
