### ISSUE TITLE
Documenting a package requires running odin-doc twice

### ISSUE THREAD

**Issue by mgavioli** [odin-lang/pkg.odin-lang.org#37]
## Actual result and workflow

When generating the documentation for a package following the steps listed in the home of this repository, in the current directory (in addition to various support `*.js` and `*.css` files) I obtain:

- a top `index.html` with links to the `base` library and to the **sources** (not the docs) of the package;
- a `<package_name>/index.html`, not linked from the previous one,  which contains a link (again to the package sources rather than to the docs) and just one line from the package's `doc.odin` but no types, no variables, no procedures....

Screen-shots of the generated HTML's for my `locale` library. **Top level** `index.html`:

![pkg-odin-issue_0_scaled](https://github.com/odin-lang/pkg.odin-lang.org/assets/1420743/bc417f8a-813f-4e6b-b8bb-ae77665e49d6)

**Nested** `index.html`:

![pkg-odin-issue_1_scaled](https://github.com/odin-lang/pkg.odin-lang.org/assets/1420743/a0c1e97f-18c7-48e2-8011-52dfeb6af142)

By running the same command from the same dir **a second time** (without deleting anything from the output directory), the above is not changed, but a new `<package_name>/<package_name>/index.html` directory and file are created with all the documentation (again not linked from any of the previous HTML files):

![pkg-odin-issue_2_scaled](https://github.com/odin-lang/pkg.odin-lang.org/assets/1420743/f283d265-d637-496f-86d7-ae65f7b91e7f)

My setup: the directory in `base_url` contains the project; a `locale` sub-dir contains the sources (`sources_url`); a `doc-gen` sub-dir contains the doc generation files (`all-local.odin`, `all-locale.odin-doc`, `odin-doc-config.json`); the docs are generated in a `docs` sub-dir.

For documentation, this is the `config.json` I'm using (which may or may not be correct, but which eventually generates the correct docs):
```
{
	"hide_base": true,
	"hide_core": true,
	"collections":
	{
		"locale":
		{
			"name": "locale",
			"source_url": "../locale",
			"base_url": "/home/mmg/Documents/projects/odin/locale",
			"root_path": "..",
			"license":
			{
				"text": "BSD-2-Clause",
				"url": "../LICENSE.md"
			},
			"home":
			{
				"title": "locale",
				"description": "locale management"
			}
		}
	}
}
```
## Expected result:

- The intended docs are obtained with a **single** run of `odin.doc[.exe]`.
- For a single-package doc, one directory and `index.html` would be enough. It may make sense to have a top-level dir and `index.html` listing the packages; particularly if the documentation spans several packages, but also with a single package, to simplify implementation.
- This top level links to the dirs with the **docs** of each package (**not the sources**; this seems to be hinted to by the current implementation, which however does not generate the docs initially and does not link to it/them in any case).
- In most cases, two levels are enough; additional levels may be related to a hierarchical directory taxonomy and should not occur with a 'flat' package in just one directory (as the case shown above).

**Comment by laytan** [comment]
This was fixed by #40
